name: Publish docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Tags for tools Image
        id: metadata-tools
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ministryofjustice/cloud-platform-tools
          tags: |
            type=ref,event=tag
    
      - name: Build and push tools image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata-tools.outputs.tags }}
      
      - name: Get Tags for env pipeline tools
        id: metadata-env-tools
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ministryofjustice/cloud-platform-pipeline-tools
          tags: |
            type=ref,event=tag
    
      - name: Build and push env pipeline tools image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          file: Dockerfile.cp-env-pipeline
          push: true
          tags: ${{ steps.metadata-env-tools.outputs.tags }}
      
      - name: Get Tags for infrastructure pipeline image
        id: metadata-infra-tools
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ministryofjustice/cloud-platform-infrastructure
          tags: |
            type=ref,event=tag
    
      - name: Build and push env pipeline tools image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          file: Dockerfile.cp-infrastructure
          push: true
          tags: ${{ steps.metadata-infra-tools.outputs.tags }}

