name: Publish docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Push tools image to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ministryofjustice/cloud-platform-tools
          tags: latest
          tag_with_ref: true
      - name: Push pipeline-tools image to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.cp-env-pipeline
          repository: ministryofjustice/cloud-platform-pipeline-tools
          tag_with_ref: true
